"""map upgrade desc

Revision ID: a43c5cc2a2c9
Revises: 32f6cbd70da3
Create Date: 2023-05-16 11:16:16.093131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43c5cc2a2c9'
down_revision = '32f6cbd70da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_about', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_column('map_about')

    # ### end Alembic commands ###
