"""remove commands?

Revision ID: c7e22157c8cd
Revises: 255fe1336bff
Create Date: 2023-05-20 01:26:04.875946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e22157c8cd'
down_revision = '255fe1336bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command_desc', sa.String(length=64), nullable=True))
        batch_op.alter_column('command_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.alter_column('command_name',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('command_desc')

    # ### end Alembic commands ###
