"""Fixed t the last_seen

Revision ID: c8a29f005589
Revises: 1812c35d9163
Create Date: 2023-05-15 17:29:21.140258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a29f005589'
down_revision = '1812c35d9163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.drop_column('lst_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lst_seen', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
